name: "Test suite"

on:
  push:
    branches: [ master, '*.x' ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2 ]
    name: PHP ${{ matrix.php }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Setup Composer token
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Cache PHPUnit results
        uses: actions/cache@v4
        with:
          path: .phpunit.result.cache
          key: ${{ runner.os }}-php-${{ matrix.php }}-phpunit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-phpunit-

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist

      - name: Execute tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml --testdox --cache-directory=.phpunit.result.cache --colors=always

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          fail_ci_if_error: true
#          verbose: true
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
